// Generated by https://quicktype.io

export interface Loan {
  tipo:             string;
  nombre:           string;
  cantidadPrestada: number;
  monto:            number;
  abonado:          number;
  id:               number;
  abonos:           number;
  saldo:            number;
  fecha:            string;
  plazos:           number;
}
