// Generated by https://quicktype.io

export interface Loan {
  tipo:             "Quincenal" | "Semanal";
  nombre:           string;
  cantidadPrestada: number;
  monto:            number;
  abonado:          number;
  id:               number;
  abonos:           number;
  saldo:            number;
  fecha:            string;
  plazos:           number;
}
export interface CreateLoan {
  tipo:             "Quincenal" | "Semanal";
  nombre:           string;
  cantidadPrestada: number;
  monto:            number;
  fecha:            Date;
  plazos:           number;
}


