// Generated by https://quicktype.io

export interface UserLoan {
  email:           string;
  id:              string;
  total:           number;
  nombre:          string;
  totalCompletado: number;
  totalRecuperar:  number;
  totalGanar:      number;
}
